### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by ghost** [kayla-lixinyi/kayla-lixinyi#1]
_

**Comment by Iman-ibrahim-88** [comment]
Delete the issue if you read this

**Comment by Iman-ibrahim-88** [comment]
Why suddenly when missing after 16 dec

**Comment by Iman-ibrahim-88** [comment]
Then post something yesterday without contacting me?

**Comment by Iman-him** [comment]
Happy birthday Kayla 🎂. You made it ❤️❤️. where are you? are you okay? I apologize for what I said and I did. Im sorry 😞 ok. 😣. can we talk please😭🤞🏻. I’m truly sorry ok🙏🏻😣.
